language: python

services:
  - docker
  -
install:
  - docker build -t multicatch/django-example-oauth .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

env:
  global:
  - secure: GFl2VQJsldZ/mCTFim/5qcE4CfQ7pHJbOC8W82wnQp2rOCrV9ErYYIMnhc65p5QwkzF8FfC0mcNoS9WIbOOyG3RuCMS5K9iZ6j9XAQGPHb9TabSCU+/yPyMtfqqbLWbKllwsShom/T9YIluwIlSg7JwW7LhPurvMSOMHmA8sUOQWkYHch6IFZc5KBZWPf+jba8ow55nnx0M9aLDfHVvuY9pQeoyKojE5+Lj1BF3bSV6bpPKdW13yOrJvdbrlNXUlCltXVtAaNAsKDjIzLOVNbLfDYUwngFAf0ACyP9PNxke1KHZvZLI6fBQmD3v5bBS0QZ3DUcoKQoyOjxVyt9yJVQsM4R4VGYyakDANnOsaB2hbLawGwLhvz8jg3VUjz8M3eN7dZnNTihIX6mK3OWRzCvvZPFoaSe315fMfW/pmjdomdTRuTbzlU54/NHpKjiscrR+F+0lOqcHk9ff8zT2mGqvlUQRtx1XLG4i3JxzLHNm3AN2dwPkqughbwmc3T+j10snQZpnA2TV6JCGoJYcVhkYCZGG7ar4TaKL7dTtVgU0OEMlsnPsGKcjG6Zs0CmqJYs4i5SLtKeRYIahaEUB+K+MI/WqgNJb2RljX/HbVE/TAIxf+cYRX0V3T2nXx23zMn2U/ZX3eMuZhVCGp4Fw4Y9QOCYbmDwytiIVu3/UEUzM=
  - secure: q9deFNGQHp1j7D8Bb3UpFbngcobwPIQ+WQGJCPre8PDY0hgs7JxF5kFBqqHu54bKKv/9XOisi0KALD5o36YtaaKNKn2kiHT/BxMbBkUMcPf3Pdy18qCl9/IPpJK7ozHkfVzuvCawr+tDdLZpLdmLQ7Swi8sgA3nCQW9ytBrY5dIpWwKiHUZRA45W/IBx/Ej/E+OShsDbyrAOYJv7hUJRugGKkAsVJEm3bn0J2jRnJ1+/DMFeP3RrQyUsc/Z58jDtHbGSXdqSCKIw2WCs28TMLOjn+/e1WGDFCr+EpL5+s0HXKWPSaj5cwhipzJQMxJXHPst6ZCsHkrndtzCFEa7DQ3A1KYpbnQ/54OjURUIQFvmcvoO3qQyYQ+5GtAyb6iZcXkAbfUyO5KeHRDqiGmLmbmJhbkpdrEsyCIo0NRV8ldK4qIO78GxJDRpNWmO5szuzLO+rCsZON8C5todOq3frpbnlZ5fykXnL3z/Sh+WlcFCQBOaGZrdyturLUYBGDp2nVCBcimOm296/XD5rS3BOkoF/hluqlW4NWiyxILFKXBZaQpg/gHozSv/sFUH+H0eXJSt9d1ZguHlnfudgbzIOGUZQVkMIzmt5n5H3l0Ya9hLPkcseGwVCp9nurMNDQTLV6EZ79ungM2J+5d3nOJcNrlLDKp4d7XnxJmEBEfl0m2M=
